import Foundation
import KLMRegistry

/// Which client-protocol surface the server exposes.
///
/// Mirrors Ollama's drop-in expectation: `ollama` enables only `/api/*`,
/// `openai` only `/v1/*`, `both` (default) enables everything. `/healthz`
/// and `/metrics` are always available regardless of mode.
public enum CompatMode: String, Sendable, CaseIterable {
    case ollama
    case openai
    case both

    public init?(label: String) {
        self.init(rawValue: label.lowercased())
    }

    /// Ollama `/api/*` endpoints active in this mode.
    public var ollamaEnabled: Bool { self == .ollama || self == .both }

    /// OpenAI `/v1/*` endpoints active in this mode.
    public var openAIEnabled: Bool { self == .openai || self == .both }
}

/// Pure response-shape builders for Ollama-compatible discovery endpoints.
///
/// These are deliberately free of NIO/channel concerns so they can be unit
/// tested directly against fixture manifests. The HTTP handler in
/// ``Server`` owns transport (streaming, status codes); this owns *shape*.
public enum OllamaCompat {
    /// Krill's own version string (kept in sync with `version` CLI output).
    public static let krillVersion = KrillVersion

    /// Ollama version we advertise to version-gated clients. Spoofable via
    /// `KRILL_OLLAMA_COMPAT_VERSION` so a client that hard-requires a newer
    /// Ollama can be unblocked without a rebuild. Default tracks a recent
    /// Ollama release that exposes the full `/api` surface we implement.
    public static var ollamaCompatVersion: String {
        ProcessInfo.processInfo.environment["KRILL_OLLAMA_COMPAT_VERSION"]
            ?? "0.12.0"
    }

    /// `GET /api/version` body. Ollama clients read `version`; we add
    /// `krill_version` so Krill-aware tooling can detect the real engine.
    public static func versionPayload() -> [String: Any] {
        [
            "version": ollamaCompatVersion,
            "krill_version": krillVersion,
        ]
    }

    /// Ollama-style `details` block shared by `/api/tags`, `/api/ps`,
    /// `/api/show`.
    public static func details(for m: ModelManifest) -> [String: Any] {
        [
            "parent_model": "",
            "format": "safetensors",
            "family": m.family.rawValue,
            "families": [m.family.rawValue],
            "parameter_size": m.params,
            "quantization_level": m.quant,
        ]
    }

    /// Capability list for `/api/show`. Sourced from the central
    /// `ModelCapabilities` registry so the same set is used here, by the
    /// engine's media gating, and by the server's pre-generation
    /// rejection. `completion` is emitted as the Ollama-compatible
    /// alias for `textGeneration` (textGeneration's `ollamaTag`).
    public static func capabilities(for m: ModelManifest) -> [String] {
        let caps = ModelCapabilities.capabilities(for: m.family)
        // Emit in a stable order so client tests can golden-match.
        return Capability.allCases
            .filter { caps.contains($0) }
            .map(\.ollamaTag)
    }

    /// A pseudo-Modelfile so `ollama show --modelfile` style clients get a
    /// non-empty, plausible document.
    public static func modelfile(for m: ModelManifest) -> String {
        """
        # Modelfile generated by Krill for \(m.name)
        # Source: \(m.source)
        FROM \(m.source)
        PARAMETER num_ctx \(m.context)
        """
    }

    /// `POST /api/show` body for an installed model. `loaded` toggles the
    /// `expires_at`-adjacent runtime hints some clients expect.
    public static func showPayload(
        for m: ModelManifest,
        verbose: Bool = false,
        directory: URL? = nil
    ) -> [String: Any] {
        var modelInfo: [String: Any] = [
            "general.architecture": m.family.rawValue,
            "general.parameter_count": m.params,
            "general.quantization_version": m.quant,
            "krill.context_length": m.context,
        ]
        if verbose {
            modelInfo["general.source"] = m.source
        }
        let ov = m.overrides
        let paramsStr = (ov?.parameters).map { p in
            p.map { "\($0.key) \($0.value)" }.joined(separator: "\n")
        } ?? "num_ctx \(m.context)"
        return [
            "license": ov?.license ?? "See model source: \(m.source)",
            "modelfile": modelfile(for: m),
            "parameters": paramsStr,
            "template": ov?.template ?? "{{ .Prompt }}",
            "system": ov?.system ?? "",
            "details": details(for: m),
            "model_info": modelInfo,
            "capabilities": capabilities(for: m),
            "support_tier": ModelCapabilities.supportTier(
                for: m.family, at: directory).rawValue,
            "modified_at": ISO8601DateFormatter().string(from: m.pulledAt),
        ]
    }

    /// One `/api/ps` model entry for the currently-loaded model.
    ///
    /// - Parameters:
    ///   - manifest: registry manifest for the loaded model, if resolvable.
    ///   - modelName: engine's loaded model name (fallback when no manifest).
    ///   - sizeBytes: resident size estimate.
    ///   - expiresAt: keep-alive eviction time (best-effort until WS-E lands).
    public static func psEntry(
        manifest: ModelManifest?,
        modelName: String,
        sizeBytes: Int64,
        expiresAt: Date
    ) -> [String: Any] {
        var entry: [String: Any] = [
            "name": modelName,
            "model": modelName,
            "size": sizeBytes,
            "size_vram": sizeBytes,
            "digest": "",
            "expires_at": ISO8601DateFormatter().string(from: expiresAt),
        ]
        if let m = manifest {
            entry["details"] = details(for: m)
        } else {
            entry["details"] = [
                "parent_model": "",
                "format": "safetensors",
                "family": "unknown",
                "families": ["unknown"],
                "parameter_size": "",
                "quantization_level": "",
            ] as [String: Any]
        }
        return entry
    }
}
