import XCTest
import MLX
@testable import KrillCore

/// Stage 1 gate for the native Whisper runtime: the log-mel front-end must
/// match `transformers.WhisperFeatureExtractor` (the correctness oracle).
///
/// The waveform is the deterministic two-sine signal generated by
/// `tools/whisper_ref.py` (3 s @ 16 kHz, 440 Hz + 880 Hz); golden values were
/// captured from that script's `WhisperFeatureExtractor(feature_size=80)`
/// output. Layout note: the reference is `feat[mel, frame]`; `WhisperMel`
/// returns `[frame, mel]`, so golden `feat[m, f]` is compared to `mel[f, m]`.
final class WhisperMelTests: XCTestCase {

    /// Reproduce the Python reference waveform exactly.
    private func refWaveform() -> [Float] {
        let sr = 16_000, n = 16_000 * 3
        return (0 ..< n).map { i in
            Float(0.5 * sin(2.0 * .pi * 440.0 * Double(i) / Double(sr))
                + 0.3 * sin(2.0 * .pi * 880.0 * Double(i) / Double(sr)))
        }
    }

    func testMelFilterBankMatchesSlaneyReference() {
        let fb = WhisperMel.melFilterBank(nMels: 80)   // [201, 80]
        XCTAssertEqual(fb.shape, [201, 80])
        // mel_filters sum ~1.999024 (transformers golden).
        XCTAssertEqual(MLX.sum(fb).item(Float.self), 1.999024, accuracy: 1e-3)
        // fb is [freq, mel]; reference printed mel_filters[1, :6] (freq row 1).
        let row1 = fb[1].asArray(Float.self)
        let goldRow1: [Float] = [0.024862594, 0.0019908219, 0, 0, 0, 0]
        for k in 0 ..< 6 {
            XCTAssertEqual(row1[k], goldRow1[k], accuracy: 1e-5)
        }
        // reference mel_filters[:6, 1] (mel column 1).
        let col1 = fb[0..., 1].asArray(Float.self)
        let goldCol1: [Float] = [0, 0.0019908219, 0.022871772, 0, 0, 0]
        for k in 0 ..< 6 {
            XCTAssertEqual(col1[k], goldCol1[k], accuracy: 1e-5)
        }
    }

    func testLogMelMatchesFeatureExtractorGolden() {
        let mel = WhisperMel.logMel(waveform: refWaveform(), nMels: 80)
        XCTAssertEqual(mel.shape, [WhisperMel.nFrames, 80])   // [3000, 80]

        // Global stats from the reference feat [80, 3000].
        XCTAssertEqual(MLX.mean(mel).item(Float.self), -0.542375, accuracy: 2e-3)
        XCTAssertEqual(MLX.max(mel).item(Float.self), 1.438204, accuracy: 2e-3)
        XCTAssertEqual(MLX.min(mel).item(Float.self), -0.561796, accuracy: 2e-3)

        // Pointwise golden: (mel_idx, frame_idx) -> value. Compared to mel[f, m].
        let golden: [(Int, Int, Float)] = [
            (0, 0, 1.039136), (0, 1, 0.527264), (0, 50, -0.561796),
            (10, 0, 1.350263), (10, 100, 1.348738),
            (40, 0, 0.617945), (40, 200, -0.561796),
            (79, 0, 0.090425), (79, 500, -0.561796),
            (20, 1499, -0.561796), (5, 2999, -0.561796),
        ]
        for (m, f, want) in golden {
            let got = mel[f, m].item(Float.self)
            XCTAssertEqual(got, want, accuracy: 3e-3, "feat[\(m),\(f)]")
        }
    }
}
